### ISSUE TITLE
CCARE-51  deploy : 인프라 환경 구축

### ISSUE THREAD

**Issue by doolysmile** [care-your-code/code-care-server#5]
## Description

> 인프라 환경 구축

## Todo

- [x] 설정 파일 작성
- [x] 파일 암호화
- [ ] git action CI 구현
- [ ] git action CD 구현
